site_name: Kinetic Trust Protocol
site_description: A framework for dynamic, physics-based authorization of autonomous agents
site_author: NMCITRA
site_url: https://nmcitra.github.io/ktp-rfc/

repo_name: nmcitra/ktp-rfc
repo_url: https://github.com/nmcitra/ktp-rfc
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/nmcitra-logo.png
  palette:
    scheme: default
    primary: indigo
    accent: indigo

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Constitution: constitution.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nmcitra/ktp-rfc

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2025 Chris Perkins / NMCITRA - Licensed under Apache 2.0
